import {normalizeIR} from "./ir.mjs";
import {renderIRCNL} from "./cnl.mjs";
import {symbolWords} from "../../../tools/lib/symbols.mjs";

export function compileFormalModule(input, {banner = true} = {}) {
  const ir = normalizeIR(input);
  const data = JSON.stringify(ir, null, 2);
  return `${banner ? "// Generated by nl-formalizer-lab. Edit the IR if desired; execution prints deterministic CNL.\n" : ""}import { pathToFileURL } from "node:url";

export const formalIR = ${data};

${symbolWords.toString()}

${renderIRCNL.toString()}

// Same structural renderer as the lab runtime (glosses are not rendered).
export function toCNL(ir = formalIR) {
  return renderIRCNL(ir);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  console.log(toCNL());
}
`;
}
